

services:
  db:
    image: mysql:5.7
    container_name: orangehrm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orange
      MYSQL_PASSWORD: orange
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: webdevops/php-apache:7.4
    container_name: orangehrm_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - orangehrm_app_data:/app
    depends_on:
      - db

volumes:
  orangehrm_app_data: